package com.stocks.product_service.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a Supplier entity that stores supplier information.
 * This entity is mapped to the 'suppliers' table in the database.
 */
@Entity // Marks this class as an entity that will be mapped to a database table
@Table(name = "suppliers") // Specifies the name of the database table for this entity
public class Supplier {

    @Id // Marks the following field as the primary key for the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key is auto-generated by the database
    @Column(name = "supplier_id") // Maps this field to a column named "supplier_id" in the database
    private Integer supplierId; // Unique identifier for the supplier entity

    @Column(name = "supplier_name", nullable = false, unique=true) // Maps this field to a column named "supplier_name" in the database, which cannot be null
    private String supplierName; // Name of the supplier

    @Column(name = "contact_number") // Maps this field to a column named "contact_number" in the database
    private String contactNumber; // Contact number of the supplier

    @Column(name = "state") // Maps this field to a column named "state" in the database
    private String state; // State where the supplier is located

    // Constructors

    /**
     * Default constructor for Supplier entity.
     */
    public Supplier() {
        // Default constructor
    }

    /**
     * Constructor for Supplier entity with parameters.
     * @param supplierName Name of the supplier.
     * @param contactNumber Contact number of the supplier.
     * @param state State where the supplier is located.
     */
    public Supplier(String supplierName, String contactNumber, String state) {
        this.supplierName = supplierName;
        this.contactNumber = contactNumber;
        this.state = state;
    }

    // Getters and Setters

    /**
     * Getter for supplierId.
     * @return The supplierId.
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * Setter for supplierId.
     * @param supplierId The supplierId to set.
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * Getter for supplierName.
     * @return The supplierName.
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Setter for supplierName.
     * @param supplierName The supplierName to set.
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    /**
     * Getter for contactNumber.
     * @return The contactNumber.
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * Setter for contactNumber.
     * @param contactNumber The contactNumber to set.
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    /**
     * Getter for state.
     * @return The state.
     */
    public String getState() {
        return state;
    }

    /**
     * Setter for state.
     * @param state The state to set.
     */
    public void setState(String state) {
        this.state = state;
    }
}
